name: integration

on: push

jobs:

  # checks:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Run Pylint
  #     run: |
  #       pip install tox
  #       tox -e pylint

  # tests:
  #   needs: checks
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     max-parallel: 8
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-16.04]
  #       python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
  #       # exclude:
  #       # # Excluded due to faulthandler bug:
  #       # # https://github.com/grantjenks/python-runstats/runs/301718278#step:5:13
  #       # - os: windows-latest
  #       #   python-version: pypy3

  #   steps:
  #   - name: Download Build Tools for Visual Studio 2019
  #     if: matrix.os == 'windows-latest'
  #     run: Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe

  #   - name: Run vs_buildtools.exe install
  #     if: matrix.os == 'windows-latest'
  #     run: ./vs_buildtools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.140 --includeRecommended.

  #   - name: Set up Python ${{ matrix.python-version }} x64
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #       architecture: x64

  #   - uses: actions/checkout@v2

  #   - name: Test with tox
  #     run: |
  #       pip install tox
  #       tox -e py

  build-linux-cp35:
    # needs: tests
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2

    - name: Install Python package dependencies
      run: /opt/python/cp35-cp35m/bin/python -m pip install tox tox-wheel

    - name: Build binary wheel
      run: /opt/python/cp35-cp35m/bin/python -m tox -e py35-cython --wheel

    - name: Apply auditwheel
      run: auditwheel repair -w .tox/dist .tox/dist/*

    - name: Remove linux wheel
      run: rm dist/*-linux_x86_64.whl

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-linux-3.5
        path: dist

  # build-linux-cp36:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   container: quay.io/pypa/manylinux2014_x86_64

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Install Python package dependencies
  #     run: /opt/python/cp36-cp36m/bin/python -m pip install cython wheel

  #   - name: Build binary wheel
  #     run: /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel

  #   - name: Apply auditwheel
  #     run: auditwheel repair -w dist dist/*

  #   - name: Remove linux wheel
  #     run: rm dist/*-linux_x86_64.whl

  #   - name: Archive dist artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: dist-linux-3.6
  #       path: dist

  # build-linux-cp37:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   container: quay.io/pypa/manylinux2014_x86_64

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Install Python package dependencies
  #     run: /opt/python/cp37-cp37m/bin/python -m pip install cython wheel

  #   - name: Build binary wheel
  #     run: /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel

  #   - name: Apply auditwheel
  #     run: auditwheel repair -w dist dist/*

  #   - name: Remove linux wheel
  #     run: rm dist/*-linux_x86_64.whl

  #   - name: Archive dist artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: dist-linux-3.7
  #       path: dist

  # build-linux-cp38:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   container: quay.io/pypa/manylinux2014_x86_64

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Install Python package dependencies
  #     run: /opt/python/cp38-cp38/bin/python -m pip install cython wheel

  #   - name: Build binary wheel
  #     run: /opt/python/cp38-cp38/bin/python setup.py bdist_wheel

  #   - name: Apply auditwheel for manylinux wheel
  #     run: auditwheel repair -w dist dist/*

  #   - name: Remove linux wheel
  #     run: rm dist/*-linux_x86_64.whl

  #   - name: Archive dist artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: dist-linux-3.8
  #       path: dist

  # build-macos:
  #   needs: tests
  #   runs-on: macos-latest
  #   strategy:
  #     max-parallel: 4
  #     matrix:
  #       python-version: [3.5, 3.6, 3.7, 3.8]

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up Python ${{ matrix.python-version }} x64
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #       architecture: x64

  #   - name: Install Python package dependencies
  #     run: pip install cython wheel

  #   - name: Build binary wheel
  #     run: python setup.py bdist_wheel

  #   - name: Archive dist artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: dist-macos-${{ matrix.python-version }}
  #       path: dist

  # build-windows:
  #   needs: tests
  #   runs-on: windows-latest
  #   strategy:
  #     max-parallel: 3
  #     matrix:
  #       python-version: [3.6, 3.7, 3.8]

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Download Build Tools for Visual Studio 2019
  #     run: Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe

  #   - name: Run vs_buildtools.exe install
  #     run: ./vs_buildtools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 --add Microsoft.VisualStudio.Component.VC.140 --includeRecommended

  #   - name: Set up Python ${{ matrix.python-version }} x64
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #       architecture: x64

  #   - name: Install Python package dependencies
  #     run: pip install cython wheel

  #   - name: Build binary wheel
  #     run: python setup.py bdist_wheel

  #   - name: Archive dist artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: dist-windows-${{ matrix.python-version }}
  #       path: dist

  # upload:
  #   if: startsWith(github.ref, 'version-')
  #   needs: [build-linux-cp35, build-linux-cp36, build-linux-cp37, build-linux-cp38, build-macos, build-windows]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8

  #   - name: Create source dist
  #     run: python setup.py sdist

  #   - name: Stage linux 3.5
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-linux-3.5
  #   - run: mv -v dist-linux-3.5/* dist/

  #   - name: Stage linux 3.6
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-linux-3.6
  #   - run: mv -v dist-linux-3.6/* dist/

  #   - name: Stage linux 3.7
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-linux-3.7
  #   - run: mv -v dist-linux-3.7/* dist/

  #   - name: Stage linux 3.8
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-linux-3.8
  #   - run: mv -v dist-linux-3.8/* dist/

  #   - name: Stage macos 3.5
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-macos-3.5
  #   - run: mv -v dist-macos-3.5/* dist/

  #   - name: Stage macos 3.6
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-macos-3.6
  #   - run: mv -v dist-macos-3.6/* dist/

  #   - name: Stage macos 3.7
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-macos-3.7
  #   - run: mv -v dist-macos-3.7/* dist/

  #   - name: Stage macos 3.8
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-macos-3.8
  #   - run: mv -v dist-macos-3.8/* dist/

  #   - name: Stage windows 3.6
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-windows-3.6
  #   - run: mv -v dist-windows-3.6/* dist/

  #   - name: Stage windows 3.7
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-windows-3.7
  #   - run: mv -v dist-windows-3.7/* dist/

  #   - name: Stage windows 3.8
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist-windows-3.8
  #   - run: mv -v dist-windows-3.8/* dist/

  #   - name: Upload with twine
  #     env:
  #       TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  #       TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  #     run: |
  #       ls -l dist/*
  #       pip install twine
  #       twine upload dist/*
